# Generated by Django 5.0.2 on 2024-02-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_name_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
