# Generated by Django 5.0.2 on 2024-02-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
